[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
privacy_pool = "G7m7QCf2m6VsaDs7GJC9wMmxCiWxmAjKN6BhakkWYi32"

[programs.devnet]
privacy_pool = "G7m7QCf2m6VsaDs7GJC9wMmxCiWxmAjKN6BhakkWYi32"

[programs.mainnet]
privacy_pool = "G7m7QCf2m6VsaDs7GJC9wMmxCiWxmAjKN6BhakkWYi32"

[registry]
url = "https://api.apr.dev"

#[provider]
#cluster = "Localnet"
#wallet = "/Users/pintu/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/Users/pintu/.config/solana/id.json"

[test]
startup_wait = 15000

[scripts]
test = "npm test"
