[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.0"

[features]
seeds = false
skip-lint = false
privacy_pool = ["zk-verify"]

[programs.localnet]
privacy_pool = "8o61scVoCHLQij6s9E4EXzbXJg58Bku9C16frkVociwP"

[programs.devnet]
privacy_pool = "8o61scVoCHLQij6s9E4EXzbXJg58Bku9C16frkVociwP"

[programs.mainnet]
privacy_pool = "8o61scVoCHLQij6s9E4EXzbXJg58Bku9C16frkVociwP"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "localnet"
wallet = "/Users/admin/.config/solana/id.json"

[test]
startup_wait = 15000

[scripts]
test = "npm test"
